builders:
  rest_api:
    import: "package:rest_api_generator/builder.dart"
    builder_factories: [ "restApiBuilder" ]
    build_extensions: { ".dart": [ "rest_api.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
